name: Check Code Quality

on: 
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  check-lint-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    -uses: actions/checkout@v5
      with
        submodules:recursive

    -name: Install Node
      uses:actions/setup-node@v5
      with
      node-version:20.x

      
      uses:actions/cache@v4
      with
      
        key:{{ runner.os }-node-${ hashFiles}('**/package-lock.json')}
        restore-keys:\
          ${{ runner.os }}-node-


      run:npmci
    
    name:
      run: npm run lint:check
 name: Check build
